ALTER TABLE quiz.video_job
ADD COLUMN IF NOT EXISTS narration_volume DOUBLE PRECISION NULL DEFAULT 1.0;

ALTER TABLE quiz.video_job
ADD COLUMN IF NOT EXISTS bgm_volume DOUBLE PRECISION NULL DEFAULT 0.08;

ALTER TABLE quiz.video_job
ADD COLUMN IF NOT EXISTS sfx_volume DOUBLE PRECISION NULL DEFAULT 1.0;

