ALTER TABLE quiz.video_job
ADD COLUMN IF NOT EXISTS voice_tone TEXT NULL DEFAULT 'calm';

ALTER TABLE quiz.video_job
ADD COLUMN IF NOT EXISTS question_rate_pct INTEGER NULL DEFAULT 100;

ALTER TABLE quiz.video_job
ADD COLUMN IF NOT EXISTS answer_rate_pct INTEGER NULL DEFAULT 100;

ALTER TABLE quiz.video_job
ADD COLUMN IF NOT EXISTS question_pause_ms INTEGER NULL DEFAULT 300;

ALTER TABLE quiz.video_job
ADD COLUMN IF NOT EXISTS answer_pause_ms INTEGER NULL DEFAULT 350;

